-- Add source and isAutoGenerated fields to leave_requests
-- source: EMPLOYEE_REQUEST (default) | TARDINESS_AUTO | MANAGER_ASSIGN
-- isAutoGenerated: true for system-generated records (e.g. tardiness offsets)

ALTER TABLE leaves.leave_requests
  ADD COLUMN IF NOT EXISTS "source"          TEXT NOT NULL DEFAULT 'EMPLOYEE_REQUEST',
  ADD COLUMN IF NOT EXISTS "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS "leave_requests_source_idx"
  ON leaves.leave_requests("source", "employeeId");
