-- Add CONSULTANT and SERVICE_PROVIDER to ContractType enum
ALTER TYPE users."ContractType" ADD VALUE IF NOT EXISTS 'CONSULTANT';
ALTER TYPE users."ContractType" ADD VALUE IF NOT EXISTS 'SERVICE_PROVIDER';
