export enum AuditAction {
  // Roles
  ROLE_CREATED               = 'ROLE_CREATED',
  ROLE_UPDATED               = 'ROLE_UPDATED',
  ROLE_DELETED               = 'ROLE_DELETED',
  ROLE_PERMISSIONS_CHANGED   = 'ROLE_PERMISSIONS_CHANGED',

  // User-Role assignments
  ROLE_ASSIGNED_TO_USER      = 'ROLE_ASSIGNED_TO_USER',
  ROLE_REVOKED_FROM_USER     = 'ROLE_REVOKED_FROM_USER',

  // Login events
  LOGIN_SUCCESS              = 'LOGIN_SUCCESS',
  LOGIN_FAILED               = 'LOGIN_FAILED',

  // Security
  ACCESS_DENIED              = 'ACCESS_DENIED',
  SUSPICIOUS_REFRESH_REUSE   = 'SUSPICIOUS_REFRESH_REUSE',

  // Clinic — Patients
  CLINIC_PATIENT_CREATED     = 'CLINIC_PATIENT_CREATED',
  CLINIC_PATIENT_UPDATED     = 'CLINIC_PATIENT_UPDATED',
  CLINIC_PATIENT_DELETED     = 'CLINIC_PATIENT_DELETED',
  CLINIC_CONSENT_SIGNED      = 'CLINIC_CONSENT_SIGNED',
  CLINIC_DOCUMENT_UPLOADED   = 'CLINIC_DOCUMENT_UPLOADED',

  // Clinic — Prosthetics
  CLINIC_PROSTHETICS_CASE_CREATED      = 'CLINIC_PROSTHETICS_CASE_CREATED',
  CLINIC_PROSTHETICS_STATUS_CHANGED    = 'CLINIC_PROSTHETICS_STATUS_CHANGED',
  CLINIC_COMMITTEE_OPINION_SUBMITTED   = 'CLINIC_COMMITTEE_OPINION_SUBMITTED',
  CLINIC_COMMITTEE_SIGNED              = 'CLINIC_COMMITTEE_SIGNED',
  CLINIC_INVENTORY_ISSUED              = 'CLINIC_INVENTORY_ISSUED',
  CLINIC_DELIVERY_COMPLETED            = 'CLINIC_DELIVERY_COMPLETED',

  // Clinic — Physio
  CLINIC_PHYSIO_CASE_CREATED           = 'CLINIC_PHYSIO_CASE_CREATED',
  CLINIC_PHYSIO_STATUS_CHANGED         = 'CLINIC_PHYSIO_STATUS_CHANGED',
  CLINIC_PHYSIO_PLAN_SIGNED            = 'CLINIC_PHYSIO_PLAN_SIGNED',
}
