import { Injectable, Logger, OnModuleInit } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class DailyClosureService implements OnModuleInit {
  private readonly logger = new Logger(DailyClosureService.name);

  constructor(private readonly prisma: PrismaService) {}

  onModuleInit() {
    this.scheduleNextRun();
  }

  /**
   * يحسب الوقت المتبقي حتى 21:00 UTC (= منتصف الليل بتوقيت الرياض UTC+3)
   * ويجدول التشغيل التلقائي التالي
   */
  private scheduleNextRun() {
    const now = new Date();
    const next = new Date(now);
    next.setUTCHours(21, 0, 0, 0);
    if (next.getTime() <= now.getTime()) {
      next.setUTCDate(next.getUTCDate() + 1);
    }
    const delayMs = next.getTime() - now.getTime();
    const delayMin = Math.round(delayMs / 60000);
    this.logger.log(`Daily closure scheduled in ${delayMin} minutes (at ${next.toISOString()})`);

    setTimeout(async () => {
      const dateStr = new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString().split('T')[0];
      this.logger.log(`Daily closure running for date: ${dateStr}`);
      try {
        const result = await this.processDayForAllEmployees(dateStr);
        this.logger.log(`Daily closure done: ${JSON.stringify(result)}`);
      } catch (err) {
        this.logger.error(`Daily closure failed: ${(err as any)?.message}`);
      }
      this.scheduleNextRun();
    }, delayMs);
  }

  /**
   * معالجة يوم كامل — يُستدعى تلقائياً أو يدوياً للاختبار
   */
  async processDayForAllEmployees(dateStr: string): Promise<{
    date: string;
    absentCreated: number;
    missingClockOutAlerts: number;
    skipped: number;
  }> {
    const date = new Date(dateStr + 'T00:00:00Z');
    const dayOfWeek = date.getUTCDay();

    // 1. جلب كل الموظفين المرتبطين بجدول دوام نشط لهذا التاريخ
    const scheduledEmployees = (await this.prisma.$queryRawUnsafe(
      `SELECT es."employeeId", ws."workDays"
       FROM attendance.employee_schedules es
       JOIN attendance.work_schedules ws ON ws.id = es."scheduleId"
       WHERE es."isActive" = true
         AND $1::date BETWEEN es."effectiveFrom"::date
             AND COALESCE(es."effectiveTo"::date, '9999-12-31'::date)`,
      dateStr,
    )) as Array<{ employeeId: string; workDays: string }>;

    // 2. تصفية من كان يومه يوم عمل فعلي
    const workingEmployeeIds = scheduledEmployees
      .filter(emp => {
        try {
          const workDays: number[] = JSON.parse(emp.workDays);
          return workDays.includes(dayOfWeek);
        } catch {
          return false;
        }
      })
      .map(emp => emp.employeeId);

    if (workingEmployeeIds.length === 0) {
      return { date: dateStr, absentCreated: 0, missingClockOutAlerts: 0, skipped: 0 };
    }

    // 3. جلب سجلات الحضور الموجودة لهذا اليوم
    const existingRecords = (await this.prisma.$queryRawUnsafe(
      `SELECT "employeeId", "clockInTime", "clockOutTime", status
       FROM attendance.attendance_records
       WHERE date = $1::date
         AND "employeeId" = ANY($2::text[])`,
      dateStr,
      workingEmployeeIds,
    )) as Array<{
      employeeId: string;
      clockInTime: Date | null;
      clockOutTime: Date | null;
      status: string;
    }>;

    const recordMap = new Map(existingRecords.map(r => [r.employeeId, r]));

    let absentCreated = 0;
    let missingClockOutAlerts = 0;
    let skipped = 0;

    for (const employeeId of workingEmployeeIds) {
      const record = recordMap.get(employeeId);

      if (!record) {
        await this.createAbsentRecord(employeeId, dateStr);
        absentCreated++;
      } else if (['ON_LEAVE', 'HOLIDAY', 'WEEKEND', 'ABSENT'].includes(record.status)) {
        skipped++;
      } else if (record.clockInTime && !record.clockOutTime) {
        await this.createMissingClockOutAlert(employeeId, dateStr);
        missingClockOutAlerts++;
      } else {
        skipped++;
      }
    }

    return { date: dateStr, absentCreated, missingClockOutAlerts, skipped };
  }

  private async createAbsentRecord(employeeId: string, dateStr: string) {
    try {
      await this.prisma.$queryRawUnsafe(
        `INSERT INTO attendance.attendance_records
           (id, "employeeId", date, status, source,
            "isManualEntry", "lateMinutes", "earlyLeaveMinutes", "deductionApplied",
            "createdAt", "updatedAt")
         VALUES
           (gen_random_uuid(), $1, $2::date, 'ABSENT', 'SYSTEM',
            false, 0, 0, false, NOW(), NOW())
         ON CONFLICT ("employeeId", date) DO NOTHING`,
        employeeId,
        dateStr,
      );

      await this.prisma.$queryRawUnsafe(
        `INSERT INTO attendance.attendance_alerts
           (id, "employeeId", date, "alertType", severity,
            message, "messageAr", status, "isAutoGenerated", "createdAt", "updatedAt")
         VALUES
           (gen_random_uuid(), $1, $2::date, 'ABSENT', 'HIGH',
            $3, $4, 'OPEN', true, NOW(), NOW())`,
        employeeId,
        dateStr,
        `Employee was absent on ${dateStr}`,
        `الموظف غائب يوم ${dateStr}`,
      );
    } catch (err) {
      this.logger.error(`Failed to create ABSENT for ${employeeId} on ${dateStr}: ${(err as any)?.message}`);
    }
  }

  private async createMissingClockOutAlert(employeeId: string, dateStr: string) {
    try {
      const existing = (await this.prisma.$queryRawUnsafe(
        `SELECT id FROM attendance.attendance_alerts
         WHERE "employeeId" = $1 AND date = $2::date AND "alertType" = 'MISSING_CLOCK_OUT'
         LIMIT 1`,
        employeeId,
        dateStr,
      )) as Array<{ id: string }>;

      if (existing.length > 0) return;

      await this.prisma.$queryRawUnsafe(
        `INSERT INTO attendance.attendance_alerts
           (id, "employeeId", date, "alertType", severity,
            message, "messageAr", status, "isAutoGenerated", "createdAt", "updatedAt")
         VALUES
           (gen_random_uuid(), $1, $2::date, 'MISSING_CLOCK_OUT', 'MEDIUM',
            $3, $4, 'OPEN', true, NOW(), NOW())`,
        employeeId,
        dateStr,
        `Employee did not clock out on ${dateStr}`,
        `الموظف لم يسجل خروجاً يوم ${dateStr}`,
      );
    } catch (err) {
      this.logger.error(`Failed to create MISSING_CLOCK_OUT for ${employeeId} on ${dateStr}: ${(err as any)?.message}`);
    }
  }
}
