-- Add UNSPECIFIED option to all optional enum fields
SET search_path TO users;

ALTER TYPE "MaritalStatus"       ADD VALUE IF NOT EXISTS 'UNSPECIFIED';
ALTER TYPE "ContractType"        ADD VALUE IF NOT EXISTS 'UNSPECIFIED';
ALTER TYPE "BloodType"           ADD VALUE IF NOT EXISTS 'UNSPECIFIED';
ALTER TYPE "EducationLevel"      ADD VALUE IF NOT EXISTS 'UNSPECIFIED';
ALTER TYPE "WorkType"            ADD VALUE IF NOT EXISTS 'UNSPECIFIED';
ALTER TYPE "ProbationPeriod"     ADD VALUE IF NOT EXISTS 'UNSPECIFIED';
ALTER TYPE "InterviewEvaluation" ADD VALUE IF NOT EXISTS 'UNSPECIFIED';
