import { Injectable, Logger } from '@nestjs/common';
import { Cron } from '@nestjs/schedule';
import { PrismaService } from '../prisma/prisma.service';
import { toLocalDateString } from '../common/utils/timezone';

@Injectable()
export class MissingStampsCron {
  private readonly logger = new Logger(MissingStampsCron.name);

  constructor(private prisma: PrismaService) {}

  /**
   * يشتغل يومياً الساعة 23:55 بتوقيت الرياض (20:55 UTC)
   * يبحث عن سجلات لها clock-in بدون clock-out ويُنشئ تنبيه MISSING_CLOCK_OUT
   */
  @Cron('55 20 * * *', { timeZone: 'UTC' })
  async detectMissingClockOut() {
    const today = toLocalDateString(new Date());
    this.logger.log(`Running MISSING_CLOCK_OUT check for date: ${today}`);

    const records = await this.prisma.$queryRaw<Array<{ id: string; employeeId: string }>>`
      SELECT id, "employeeId"
      FROM attendance.attendance_records
      WHERE date = ${today}::date
        AND "clockInTime" IS NOT NULL
        AND "clockOutTime" IS NULL
    `;

    for (const r of records) {
      await this.prisma.$executeRaw`
        INSERT INTO attendance.attendance_alerts
          (id, "employeeId", date, "alertType", severity, message,
           "attendanceRecordId", status, "isAutoGenerated", "createdAt", "updatedAt")
        VALUES
          (gen_random_uuid(), ${r.employeeId}, ${today}::date,
           'MISSING_CLOCK_OUT', 'HIGH',
           'لا توجد بصمة خروج لهذا اليوم',
           ${r.id}, 'OPEN', true, NOW(), NOW())
        ON CONFLICT DO NOTHING
      `.catch(() => {});
    }

    this.logger.log(`Generated MISSING_CLOCK_OUT alerts for ${records.length} records`);
  }
}
