CREATE TABLE clinic_prosthetics.gait_analysis_forms (
  "id"                          TEXT         NOT NULL,
  "caseId"                      TEXT         NOT NULL,
  "sessionDate"                 TIMESTAMP(3),
  "suspensionSystem"            TEXT[]       NOT NULL DEFAULT ARRAY[]::TEXT[],
  "socketBearing"               TEXT,
  "kneeJointType"               TEXT,
  "footType"                    TEXT,
  "patientComplaints"           TEXT[]       NOT NULL DEFAULT ARRAY[]::TEXT[],
  "painIntensity"               INTEGER,
  "alignmentCheck"              TEXT,
  "hasRomLimitations"           BOOLEAN,
  "hasHipFlexionContracture"    BOOLEAN,
  "hasKneeFlexionContracture"   BOOLEAN,
  "weakHipAbductors"            BOOLEAN,
  "weakHipExtensors"            BOOLEAN,
  "weakTrunkMuscles"            BOOLEAN,
  "otherWeakness"               TEXT,
  "trunkStability"              TEXT,
  "abdominalControl"            TEXT,
  "pelvicControl"               TEXT,
  "sittingBalance"              TEXT,
  "standingBalance"             TEXT,
  "assistiveDevice"             TEXT,
  "speedMs"                     DOUBLE PRECISION,
  "cadence"                     INTEGER,
  "stepLengthProsCm"            DOUBLE PRECISION,
  "stepLengthSoundCm"           DOUBLE PRECISION,
  "stancePercProsthetic"        DOUBLE PRECISION,
  "stancePercSound"             DOUBLE PRECISION,
  "symmetry"                    TEXT,
  "initialContact"              JSONB,
  "loadingResponse"             JSONB,
  "midStance"                   JSONB,
  "terminalStance"              JSONB,
  "preSwing"                    JSONB,
  "swingPhase"                  JSONB,
  "gaitNotes"                   TEXT,
  "prostheticIssues"            TEXT[]       NOT NULL DEFAULT ARRAY[]::TEXT[],
  "mainProblem"                 TEXT,
  "likelyCauses"                TEXT[]       NOT NULL DEFAULT ARRAY[]::TEXT[],
  "recommendations"             TEXT[]       NOT NULL DEFAULT ARRAY[]::TEXT[],
  "rehabPlan"                   JSONB,
  "rehabNotes"                  TEXT,
  "examinerProsthetistId"       TEXT,
  "prosthetistSignatureUrl"     TEXT,
  "examinerPhysiotherapistId"   TEXT,
  "physiotherapistSignatureUrl" TEXT,
  "notes"                       TEXT,
  "createdAt"                   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"                   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "gait_analysis_forms_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "gait_analysis_forms_caseId_fkey"
    FOREIGN KEY ("caseId") REFERENCES clinic_prosthetics.prosthetics_cases("id")
    ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "gait_analysis_forms_caseId_idx" ON clinic_prosthetics.gait_analysis_forms("caseId");
