-- Migration: expand medical history fields to match paper form
ALTER TABLE clinic_podiatry.podiatry_receptions
  ADD COLUMN IF NOT EXISTS "currentMedications"        TEXT,
  ADD COLUMN IF NOT EXISTS "previousDiagnoses"         TEXT,
  ADD COLUMN IF NOT EXISTS "herbalPreparations"        BOOLEAN,
  ADD COLUMN IF NOT EXISTS "herbalPreparationsDetails" TEXT,
  ADD COLUMN IF NOT EXISTS "otherHealthProblems"       TEXT,
  ADD COLUMN IF NOT EXISTS "doctorRestrictions"        TEXT,
  ADD COLUMN IF NOT EXISTS "smoker"                    BOOLEAN,
  ADD COLUMN IF NOT EXISTS "everSmoked"                BOOLEAN,
  ADD COLUMN IF NOT EXISTS "smokingFrequency"          TEXT,
  ADD COLUMN IF NOT EXISTS "hasPacemaker"              BOOLEAN,
  ADD COLUMN IF NOT EXISTS "isPregnant"                BOOLEAN,
  ADD COLUMN IF NOT EXISTS "allergyToAdhesives"        BOOLEAN,
  ADD COLUMN IF NOT EXISTS "surgeries"                 JSONB NOT NULL DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS "hadPhysicalTherapy"        BOOLEAN,
  ADD COLUMN IF NOT EXISTS "hasOtherTreatments"        BOOLEAN,
  ADD COLUMN IF NOT EXISTS "radiographyTypes"          TEXT[]  NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS "radiographyOther"          TEXT,
  ADD COLUMN IF NOT EXISTS "radiographyResults"        TEXT,
  ADD COLUMN IF NOT EXISTS "hasNewAnalysis"            BOOLEAN,
  ADD COLUMN IF NOT EXISTS "newAnalysisDate"           TEXT,
  ADD COLUMN IF NOT EXISTS "hasOldAnalysis"            BOOLEAN,
  ADD COLUMN IF NOT EXISTS "oldAnalysisDate"           TEXT,
  ADD COLUMN IF NOT EXISTS "boneDensityScan"           BOOLEAN,
  ADD COLUMN IF NOT EXISTS "hospitalizedPastYear"      BOOLEAN;
