import { Module } from '@nestjs/common';
import { HttpModule } from '@nestjs/axios';
import { ProxyService } from './proxy.service';
import {
  AuthProxyController,
  UsersProxyController,
  EmployeesProxyController,
  DepartmentsProxyController,
  RolesProxyController,
  PermissionsProxyController,
  JobTitlesProxyController,
  JobGradesProxyController,
  LeaveRequestsProxyController,
  LeaveBalancesProxyController,
  LeaveTypesProxyController,
  HolidaysProxyController,
  WorkSchedulesProxyController,
  AttendanceRecordsProxyController,
  AttendanceAlertsProxyController,
  AttendanceJustificationsProxyController,
  EmployeeSchedulesProxyController,
  EvaluationPeriodsProxyController,
  EvaluationCriteriaProxyController,
  EvaluationFormsProxyController,
  PeerEvaluationsProxyController,
  EmployeeGoalsProxyController,
  RequestsProxyController,
  AttendanceReportsProxyController,
  CustodiesProxyController,
  BiometricDevicesProxyController,
  EmployeeFingerprintsProxyController,
  EmployeeAttendanceConfigProxyController,
  IclockProxyController,
  JobApplicationsProxyController,
} from './proxy.controller';

@Module({
  imports: [HttpModule],
  controllers: [
    AuthProxyController,
    UsersProxyController,
    EmployeesProxyController,
    DepartmentsProxyController,
    RolesProxyController,
    PermissionsProxyController,
    JobTitlesProxyController,
    JobGradesProxyController,
    LeaveRequestsProxyController,
    LeaveBalancesProxyController,
    LeaveTypesProxyController,
    HolidaysProxyController,
    WorkSchedulesProxyController,
    AttendanceRecordsProxyController,
    AttendanceAlertsProxyController,
    AttendanceJustificationsProxyController,
    EmployeeSchedulesProxyController,
    EvaluationPeriodsProxyController,
    EvaluationCriteriaProxyController,
    EvaluationFormsProxyController,
    PeerEvaluationsProxyController,
    EmployeeGoalsProxyController,
    RequestsProxyController,
    AttendanceReportsProxyController,
    CustodiesProxyController,
    BiometricDevicesProxyController,
    EmployeeFingerprintsProxyController,
    EmployeeAttendanceConfigProxyController,
    IclockProxyController,
    JobApplicationsProxyController,
  ],
  providers: [ProxyService],
})
export class ProxyModule {}
