-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "attendance";

-- CreateTable: work_schedules
CREATE TABLE "attendance"."work_schedules" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "nameAr" TEXT NOT NULL,
    "nameEn" TEXT,
    "description" TEXT,
    "workStartTime" TEXT NOT NULL,
    "workEndTime" TEXT NOT NULL,
    "breakStartTime" TEXT,
    "breakEndTime" TEXT,
    "breakDurationMin" INTEGER NOT NULL DEFAULT 60,
    "workDays" TEXT NOT NULL DEFAULT '[0,1,2,3,4]',
    "lateToleranceMin" INTEGER NOT NULL DEFAULT 15,
    "earlyLeaveToleranceMin" INTEGER NOT NULL DEFAULT 15,
    "allowOvertime" BOOLEAN NOT NULL DEFAULT false,
    "maxOvertimeHours" DOUBLE PRECISION,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "work_schedules_pkey" PRIMARY KEY ("id")
);

-- CreateTable: employee_schedules
CREATE TABLE "attendance"."employee_schedules" (
    "id" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "scheduleId" TEXT NOT NULL,
    "effectiveFrom" TIMESTAMP(3) NOT NULL,
    "effectiveTo" TIMESTAMP(3),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "employee_schedules_pkey" PRIMARY KEY ("id")
);

-- CreateTable: custom_work_schedules
CREATE TABLE "attendance"."custom_work_schedules" (
    "id" TEXT NOT NULL,
    "scheduleId" TEXT NOT NULL,
    "nameAr" TEXT NOT NULL,
    "nameEn" TEXT,
    "description" TEXT,
    "workStartTime" TEXT NOT NULL,
    "workEndTime" TEXT NOT NULL,
    "breakStartTime" TEXT,
    "breakEndTime" TEXT,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "employeeIds" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "custom_work_schedules_pkey" PRIMARY KEY ("id")
);

-- CreateTable: attendance_records
CREATE TABLE "attendance"."attendance_records" (
    "id" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "clockInTime" TIMESTAMP(3),
    "clockOutTime" TIMESTAMP(3),
    "workedMinutes" INTEGER,
    "overtimeMinutes" INTEGER,
    "breakMinutes" INTEGER,
    "status" TEXT NOT NULL DEFAULT 'PRESENT',
    "lateMinutes" INTEGER NOT NULL DEFAULT 0,
    "earlyLeaveMinutes" INTEGER NOT NULL DEFAULT 0,
    "clockInLocation" TEXT,
    "clockOutLocation" TEXT,
    "clockInIp" TEXT,
    "clockOutIp" TEXT,
    "isManualEntry" BOOLEAN NOT NULL DEFAULT false,
    "manualEntryBy" TEXT,
    "manualEntryReason" TEXT,
    "approvalStatus" TEXT,
    "approvedBy" TEXT,
    "approvedAt" TIMESTAMP(3),
    "approvalNotes" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "attendance_records_pkey" PRIMARY KEY ("id")
);

-- CreateTable: attendance_alerts
CREATE TABLE "attendance"."attendance_alerts" (
    "id" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "alertType" TEXT NOT NULL,
    "severity" TEXT NOT NULL DEFAULT 'MEDIUM',
    "message" TEXT NOT NULL,
    "messageAr" TEXT,
    "attendanceRecordId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'OPEN',
    "resolvedBy" TEXT,
    "resolvedAt" TIMESTAMP(3),
    "resolutionNotes" TEXT,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "attendance_alerts_pkey" PRIMARY KEY ("id")
);

-- CreateTable: attendance_settings
CREATE TABLE "attendance"."attendance_settings" (
    "id" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "attendance_settings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex: work_schedules
CREATE UNIQUE INDEX "work_schedules_code_key" ON "attendance"."work_schedules"("code");

-- CreateIndex: employee_schedules
CREATE INDEX "employee_schedules_employeeId_idx" ON "attendance"."employee_schedules"("employeeId");
CREATE INDEX "employee_schedules_scheduleId_idx" ON "attendance"."employee_schedules"("scheduleId");
CREATE UNIQUE INDEX "employee_schedules_employeeId_scheduleId_effectiveFrom_key" ON "attendance"."employee_schedules"("employeeId", "scheduleId", "effectiveFrom");

-- CreateIndex: custom_work_schedules
CREATE INDEX "custom_work_schedules_scheduleId_idx" ON "attendance"."custom_work_schedules"("scheduleId");
CREATE INDEX "custom_work_schedules_startDate_endDate_idx" ON "attendance"."custom_work_schedules"("startDate", "endDate");

-- CreateIndex: attendance_records
CREATE INDEX "attendance_records_employeeId_idx" ON "attendance"."attendance_records"("employeeId");
CREATE INDEX "attendance_records_date_idx" ON "attendance"."attendance_records"("date");
CREATE INDEX "attendance_records_status_idx" ON "attendance"."attendance_records"("status");
CREATE UNIQUE INDEX "attendance_records_employeeId_date_key" ON "attendance"."attendance_records"("employeeId", "date");

-- CreateIndex: attendance_alerts
CREATE INDEX "attendance_alerts_employeeId_idx" ON "attendance"."attendance_alerts"("employeeId");
CREATE INDEX "attendance_alerts_date_idx" ON "attendance"."attendance_alerts"("date");
CREATE INDEX "attendance_alerts_status_idx" ON "attendance"."attendance_alerts"("status");
CREATE INDEX "attendance_alerts_alertType_idx" ON "attendance"."attendance_alerts"("alertType");

-- CreateIndex: attendance_settings
CREATE UNIQUE INDEX "attendance_settings_key_key" ON "attendance"."attendance_settings"("key");

-- AddForeignKey: employee_schedules -> work_schedules
ALTER TABLE "attendance"."employee_schedules" ADD CONSTRAINT "employee_schedules_scheduleId_fkey" FOREIGN KEY ("scheduleId") REFERENCES "attendance"."work_schedules"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey: custom_work_schedules -> work_schedules
ALTER TABLE "attendance"."custom_work_schedules" ADD CONSTRAINT "custom_work_schedules_scheduleId_fkey" FOREIGN KEY ("scheduleId") REFERENCES "attendance"."work_schedules"("id") ON DELETE CASCADE ON UPDATE CASCADE;
